FROM arm64v8/nginx:1.23.0-alpine

ENV NGINX_PORT 80
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./presta.conf /etc/nginx/conf.d

WORKDIR /var/www/html

RUN chown nginx:nginx -R /var/www/html
RUN chmod 775 -R /var/www/html

EXPOSE 80